name: build from source

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 3 1 * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - arm64
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Extract wine version
        run: |
          git clone --depth=1 --shallow-submodules git://source.winehq.org/git/wine.git
          WINE_VER="$(awk '{print $3}' wine/VERSION)"
          if echo "${WINE_VER}" | grep -q -E "^[0-9]+(\.[0-9]+)+(-\S+)*$"; then
              echo "Found wine version '${WINE_VER}'"
              echo "wine_ver=${WINE_VER}" >> $GITHUB_ENV
          else
              echo "ERROR: Unable to determine wine version"
              exit 1
          fi
      -
        name: Generate timestamp
        run: |
          TIMESTAMP="$(date +"%Y%m%d")"
          echo "Timestamp: ${TIMESTAMP}"
          echo "timestamp=${TIMESTAMP}" >> $GITHUB_ENV
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.build_from_source
          platforms: linux/${{ matrix.platform }}
          push: true
          tags:
            scottyhardy/docker-wine:${{ matrix.platform }},
            scottyhardy/docker-wine:devel-${{ env.wine_ver }}-${{ matrix.platform }},
            scottyhardy/docker-wine:devel-${{ env.wine_ver }}-${{ matrix.platform }}-${{ env.timestamp }}
