name: build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 3 * * SUN'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        wine_branch:
          - stable
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and export to local Docker instance
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: docker-wine:latest
      -
        name: Test
        run: |
          ./docker-wine --local --rm --xvfb --notty winetricks -q dotnet40
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Extract wine version
        env:
          WINE_BRANCH: ${{ matrix.wine_branch }}
        run: |
          WINE_VER="$(docker run --rm docker-wine /bin/bash -c "dpkg -s wine-${WINE_BRANCH} \
          | grep '^Version:\s' | awk '{print \$2}' | sed -E 's/~.*$//'" | tr -d "\r")"
          if echo "${WINE_VER}" | grep -q -E "^[0-9]+(\.[0-9]+)*$"; then
              echo "Found wine version '${WINE_VER}'"
              echo "wine_ver=${WINE_VER}" >> $GITHUB_ENV
          else
              echo "ERROR: Unable to determine wine version"
              exit 1
          fi
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: scottyhardy/docker-wine:latest,
            scottyhardy/docker-wine:${{ matrix.wine_branch }},
            scottyhardy/docker-wine:${{ matrix.wine_branch }}-${{ env.wine_ver }}
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: scottyhardy/docker-wine
