name: build hangover on arm64

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 3 * * TUE'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Checkout hangover repo
        uses: actions/checkout@v2
        with:
          repository: AndreRH/hangover
          path: hangover
          submodules: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build hangover and export to local Docker instance
        uses: docker/build-push-action@v2
        with:
          context: hangover
          file: hangover/Dockerfile.cross_arm64
          load: true
          tags: hangover-builder
      -
        name: Extract build files
        run: docker run --rm hangover-builder tar -C /root/hangover/ --exclude-vcs -czf - . > hangover.tar.gz
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Extract wine version
        id: wine_ver
        run: |
          WINE_VER="$(docker run --rm docker-wine /bin/bash -c "wine --version | sed -E 's/^wine-//'")"
          if echo "${WINE_VER}" | grep -q -E "^[0-9]+(\.[0-9]+)+(-\S+)*$"; then
              echo "Found wine version '${WINE_VER}'"
              echo "::set-output name=value::${WINE_VER}"
          else
              echo "ERROR: Unable to determine wine version"
              exit 1
          fi
      -
        name: Generate timestamp
        id: timestamp
        run: |
          TIMESTAMP="$(date +"%Y%m%d")"
          echo "Timestamp: ${TIMESTAMP}"
          echo "::set-output name=value::${TIMESTAMP}"
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.build_from_source
          push: true
          tags:
            scottyhardy/docker-wine:hangover-arm64,
            scottyhardy/docker-wine:hangover-wine-${{ steps.wine_ver.outputs.value }}-arm64,
            scottyhardy/docker-wine:hangover-wine-${{ steps.wine_ver.outputs.value }}-arm64-${{ steps.timestamp.outputs.value }},
          target: hangover
